source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SportBuddy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen', '6.5.1'
  pod 'SwiftLint', '0.48.0'
  pod 'GoogleMLKit/PoseDetectionAccurate', '3.1.0'

  # Pods for SportBuddy

  target 'SportBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportBuddyUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end